spring:
  application:
    name: security-services
    cloud:
      config:
        uri: http://localhost:8888:eureka

server:
  port: 8088
---
spring:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  resources:
    chain:
      enabled: true
management:
  security:
    enabled: true

